Fix order of build phases; Xcode 13 complains about cycle in iOS target
Fix order for all targets, even though not all caused an error.

For reference, here is the error given by Xcode:

error: Cycle inside POLocalizedString iOS; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.
Cycle details:
→ Target 'POLocalizedString iOS' has link command with output '/Users/lauri/Library/Developer/Xcode/DerivedData/POLocalizedString-bblgflvghsrckvcppvpboendqxqn/Build/Products/Debug-iphonesimulator/POLocalizedString.framework/POLocalizedString'
○ Target 'POLocalizedString iOS' has compile command for Swift source files
○ Target 'POLocalizedString iOS' has copy command from '/Users/lauri/POLocalizedString/Framework/POLocalizedString-umbrella.h' to '/Users/lauri/Library/Developer/Xcode/DerivedData/POLocalizedString-bblgflvghsrckvcppvpboendqxqn/Build/Products/Debug-iphonesimulator/POLocalizedString.framework/Headers/POLocalizedString-umbrella.h'
○ Target 'POLocalizedString iOS' has compile command with input '/Users/lauri/POLocalizedString/POLocalizedString/Gettext.mm'